name: Build and Test

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Lint code
        run: yarn eslint

      - name: Build Astro
        run: yarn build

      #   # Build Storybook (currently hangs)
      # - name: Build Storybook
      #   run: yarn build-storybook

      - name: Run tests
        run: yarn test
