name: Build and Test

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Specify your Node.js version
          cache: 'yarn'

      # Install dependencies
      - name: Install dependencies
        run: yarn install

      # Build the project
      - name: Build the project
        run: yarn build

      # Run tests
      - name: Run tests
        run: yarn test
